info:
    title: github.com/aide-cloud/gin-plus
    version: v0.1.6
openapi: 3.0.3
paths:
    /info/:id:
        get:
            operationId: GetInfo
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                        title: Id
                                    name:
                                        type: string
                                        title: Name
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: Id
                - name: name
                  in: query
                  schema:
                    type: string
                    title: Name
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                data:
                                    type: array
                                    title: Data
                                    items:
                                        type: object
        post:
            operationId: PostInfo
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                        title: Id
                                    name:
                                        type: string
                                        title: Name
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: Id
                - name: name
                  in: query
                  schema:
                    type: string
                    title: Name
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                data:
                                    type: array
                                    title: Data
                                    items:
                                        type: object
        put:
            operationId: PutInfo
            responses:
                200:
                    description: ""
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                        title: Id
                                    name:
                                        type: string
                                        title: Name
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    title: Id
                - name: name
                  in: query
                  schema:
                    type: string
                    title: Name
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                data:
                                    type: array
                                    title: Data
                                    items:
                                        type: object
